// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicServer.Models.Database;

namespace MusicServer.Migrations
{
    [DbContext(typeof(MusicDBContext))]
    [Migration("20200612125014_MusicInit")]
    partial class MusicInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicServer.Models.Database.MusicAsset", b =>
                {
                    b.Property<string>("Name");

                    b.Property<string>("Uri");

                    b.HasKey("Name");

                    b.ToTable("MusicAssets");
                });

            modelBuilder.Entity("MusicServer.Models.Database.MusicInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<string>("ContractAddress");

                    b.Property<int>("CreatureType");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<long>("LicenceId");

                    b.Property<string>("Name");

                    b.Property<long>("OwnerId");

                    b.Property<int>("OwnerType");

                    b.Property<string>("PublishingYear");

                    b.Property<string>("Title");

                    b.Property<string>("TransactionHash");

                    b.Property<int>("TransactionStatus");

                    b.HasKey("Id");

                    b.ToTable("MusicInfos");
                });

            modelBuilder.Entity("MusicServer.Models.Database.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ActivationCode");

                    b.Property<string>("ConfirmPassword");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("EmailID");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsEmailVerified");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("ResetPasswordCode");

                    b.Property<int>("userType");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
